qr_tv_show_manager_homepage:
    path:     /
    defaults: { _controller: QRTvShowManagerBundle:Note:read }
qr_tv_show_manager_note:
    path:     /note
    defaults: { _controller: QRTvShowManagerBundle:Note:read }

qr_tv_show_manager_tvShow_read:
    path:     /tvShow
    defaults: { _controller: QRTvShowManagerBundle:TvShow:read }
qr_tv_show_manager_tvShow_add:
    path:     /tvShow/add
    defaults: { _controller: QRTvShowManagerBundle:TvShow:add }
qr_tv_show_manager_tvShow_update:
    path:     /tvShow/update/{id}
    defaults:
        _controller: QRTvShowManagerBundle:TvShow:update
        id:      1
    requirements:
        id:   \d+
qr_tv_show_manager_tvShow_delete:
    path:     /tvShow/delete/{id}
    defaults:
        _controller: QRTvShowManagerBundle:TvShow:delete
        id:      1
    requirements:
        id:   \d+

qr_tv_show_manager_episode_read:
    path:     /episode/{id}
    defaults:
        _controller: QRTvShowManagerBundle:Episode:read
        id:      1
    requirements:
        id:   \d+
qr_tv_show_manager_episode_add:
    path:     /episode/add/{id}
    defaults:
        _controller: QRTvShowManagerBundle:Episode:add
        id:      1
    requirements:
        id:   \d+
qr_tv_show_manager_episode_update:
    path:     /episode/update/{id}
    defaults:
        _controller: QRTvShowManagerBundle:Episode:update
        id:      1
    requirements:
        id:   \d+
qr_tv_show_manager_episode_delete:
    path:     /episode/delete/{id}
    defaults:
        _controller: QRTvShowManagerBundle:Episode:delete
        id:      1
    requirements:
        id:   \d+