<?php

namespace TvShowManagerBundle\Repository;
use TvShowManagerBundle\Entity\TvShow;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{
    public function listTvShow()
    {
        $em = $this->getDoctrine()->getManager();

        $show = $em->getRepository('TvShowManagerBundle:TvShow')
            ->findAll();

        return $show;

    }

    public function addTvShow($name, $type, $url, $year)
    {
        $em = $this->getDoctrine()->getManager();

        $show = new TvShow();

        $show->setName($name);
        $show->setType($type);
        $show->setUrl($url);
        $show->setYear($year);

        $em->persist($show);

        $em->flush();
    }

    public function updateTvShow($id, $name, $type, $url, $year)
    {
        $em = $this->getDoctrine()->getManager();

        $show= $em->getRepository('TvShowManagerBundle:TvShow')->find($id);

        $show->setName($name);
        $show->setType($type);
        $show->setUrl($url);
        $show->setYear($year);

        $em->flush();

    }

    public function deleteTvShow($id)
    {
        $em = $this->getDoctrine()->getManager();

        $show= $em->getRepository('TvShowManagerBundle:TvShow')->find($id);

        $em->remove($show);

        $em->flush();
    }
}
