tvshowmanager:
    resource: "@TvShowManagerBundle/Controller/"
    type:     annotation
    prefix:   /

subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

