tv_show_manager:
    resource: "@TVShowManagerBundle/Controller/"
    type:     annotation
    prefix:   /



subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

