TvShow\ManagerBundle\Entity\TvShow:
    type: entity
    table: null
    repositoryClass: TvShow\ManagerBundle\Repository\TvShowRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        url:
            type: string
            length: 255
        year:
            type: integer
    lifecycleCallbacks: {  }


